modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/MoosaSharwaan/Applied_Quartermaster/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/MoosaSharwaan/Applied_Quartermaster"
    authors="${mod_authors}"
    logoFile="logo.png"
    description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="REQUIRED"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="REQUIRED"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    type="REQUIRED"
    versionRange="[26.1.8-alpha,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2wtlib"
    type="OPTIONAL"
    versionRange="[26.1.0-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="OPTIONAL"
    versionRange="[15.0.0,)"
    ordering="NONE"
    side="BOTH"
